Log improvements
sivaprasadreddy/techbuzz pull request #74
Opened 2023-05-27 06:59 UTC by maelstrom0x8

This PR adds logging statements to the controller methods in order to capture HTTP details.

2023-05-27 16:36 UTC, sivaprasadreddy requested changes
Thanks for the PR.
Could you please look into the review comments?

2023-05-27 16:36 UTC, sivaprasadreddy commented on techbuzz/src/main/java/com/sivalabs/techbuzz/posts/web/controllers/AddVoteController.java
> +                "POST /partials/add-vote - Vote added by User id: {} for Post id: {}",
No need to include HTTP Method and URL pattern in logs.

2023-05-27 16:36 UTC, sivaprasadreddy commented on techbuzz/src/main/java/com/sivalabs/techbuzz/posts/web/controllers/ViewCategoryController.java
> +            log.warn("No posts found for category: {}", categorySlug);
These 2 log statements can be combined into a single one:

log.warn("No posts found for category: {}, page:{}. Redirecting to last page", categorySlug, page);

2023-05-27 16:36 UTC, sivaprasadreddy commented on techbuzz/src/main/java/com/sivalabs/techbuzz/users/web/controllers/EmailVerificationController.java
> +        logger.info("GET /verify-email - Verifying email {} with token: {}", email, token);
"token" is a sensitive information, should not be logged.

2023-05-27 16:36 UTC, sivaprasadreddy commented on techbuzz/src/main/java/com/sivalabs/techbuzz/users/web/controllers/ResendVerificationController.java
> +                logger.info("Sent email verification link");
Update to logger.info("Sent email verification link to {}", email);

2023-05-27 17:05 UTC, maelstrom0x8 commented
Alright sir. I'm on it.

2023-05-27 19:02 UTC, maelstrom0x8 commented
hello @sivaprasadreddy 
please review the updated changes. thank you!

2023-05-28 03:10 UTC, sivaprasadreddy commented
@maelstrom0x8 The changes looks good.
However, there are code formatting issue.
Please run "./mvnw spotless:apply" which will auto format the code and commit the changes.

2023-05-28 11:26 UTC, maelstrom0x8 commented
done.

2023-05-28 14:46 UTC, merged